### ISSUE TITLE
 No support for reading file type application/json - support for csv or xls only

### ISSUE THREAD

**Issue by IT-mark** [okfn/dataconverters#106]
Hi 

I ejecuted =

root@localhost CONVERTIDOR]# dataconvert 2015.json _.csv

obtaining = 

Traceback (most recent call last):
  File "/usr/bin/dataconvert", line 9, in <module>
    load_entry_point('dataconverters==0.4', 'console_scripts', 'dataconvert')()
  File "build/bdist.linux-x86_64/egg/dataconverters/cli.py", line 55, in main
  File "build/bdist.linux-x86_64/egg/dataconverters/__init__.py", line 74, in _dataconvert

ValueError: No support for reading file type application/json - support for csv or xls only 

---> ¿ Is it planned to convert json to other kind of files ? thanks

**Comment by mtarinalfatec** [comment]
Hi
Do you know an alternate program that let's me to convert json to other kind of files? 
thanks
